package routers

import (
	"github.com/gin-contrib/pprof"
	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger" //nolint: goimports
	"github.com/swaggo/gin-swagger/swaggerFiles"

	"strawberrymaker/app/api"
	"strawberrymaker/app/api/http/v1/user"
	"strawberrymaker/pkg/conf"
	"strawberrymaker/pkg/snake"

	// import swagger handler
	_ "strawberrymaker/docs" // docs is generated by Swag CLI, you have to import it.
	"strawberrymaker/router/middleware"
)

// Load loads the middlewares, routes, handlers.
func Load(g *gin.Engine, mw ...gin.HandlerFunc) *gin.Engine {
	// 使用中间件
	g.Use(middleware.NoCache)
	g.Use(middleware.Options)
	g.Use(middleware.Secure)
	g.Use(middleware.Logging())
	g.Use(middleware.RequestID())
	g.Use(mw...)

	// 404 Handler.
	g.NoRoute(api.RouteNotFound)
	g.NoMethod(api.RouteNotFound)

	userGroup := g.Group("/api/v1")

	{ // 静态资源，主要是图片
		userGroup.Static("/static", "./static")
		// 返回404，仅在test环境下开启，线上关闭
		if conf.Conf.App.RunMode == snake.ModeDebug {
			// swagger api docs
			userGroup.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
			// pprof router 性能分析路由
			// 默认关闭，开发环境下可以打开
			// 访问方式: HOST/debug/pprof
			// 通过 HOST/debug/pprof/profile 生成profile
			// 查看分析图 go tool pprof -http=:5000 profile
			// see: https://github.com/gin-contrib/pprof
			pprof.Register(g)
		} else {
			// disable swagger docs for release  env=release
			userGroup.GET("/swagger/*any", ginSwagger.DisablingWrapHandler(swaggerFiles.Handler, "env"))
		}

		// 认证相关路由
		userGroup.POST("/register", user.Register)
		userGroup.POST("/login", user.Login)
		userGroup.POST("/login/phone", user.PhoneLogin)
		userGroup.GET("/vcode", user.VCode)

		u := userGroup.Group("/users")
		u.Use(middleware.AuthMiddleware())
		{
			u.POST("/update", user.Update)
			u.GET("/profile", user.Profile)
			u.POST("/follow", user.Follow)
			u.GET("/following", user.FollowList)
			u.GET("/followers", user.FollowerList)
		}
	}
	return g
}
